routes/statement.rb
例えば削除済みの発言にわかるわしようとするとエラーになるので、それを回避。問題なさそうならmergeしてください > @Echos
=> fix error on no body in a statement

routes/statement.rb
現状特に何も使ってないので実害はないですが、#99 の絡みで自己埋め込みに対応しようとすると欲しくなりそう。
=> /statement/記事ID.json なURLがマッチしなくなっていたので修正

assets/js/jquery.auto-link.js
以下2点を修正しました
- タイムラインに同じツイートが複数貼られるとdivのidが被って埋め込みが重複する不具合の修正
- デフォルトのスタイルだと文字が大き過ぎるので標準の85%のフォントサイズに強制
=> twitter埋め込みのコード修正

assets/js/massr.js
submitStamp.removeAttr('id'); が本質であとは例外処理や重複処理の排除
=> スタンプボタンを押したあと画像ポップアップもスタンプリストになってしまう問題を修正

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6088210735724993565">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6088210735724993565">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20151231061622

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6095820879182890165">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6095820879182890165">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160121061626

assets/css/default.css, assets/js/jquery.auto-link.js, assets/js/massr.js, assets/js/massr.templates.js, views/statement.haml
本文中に同一ホストのmassrのstatementを書くと展開して表示する機能を追加。
http/httpsも同一でないと有効にならない。
この機能実装で同一statementが複数箇所に現れるようになったため、各種とりまわしをid属性からclass属性へ変更。
=> Embed massr statement

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6100894313742429378">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6100894313742429378">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160204061643

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6105967742407527937">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6105967742407527937">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160218061647

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6111041172592971092">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6111041172592971092">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160303061708

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6116114604417852749">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6116114604417852749">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160317061639

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6141481760957055871">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6141481760957055871">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160526061709

helpers/init.rb, views/popup_photo.haml
=> Fix photo to stamp

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6149091895661730201">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6149091895661730201">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160616061721

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6154165328202047372">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6154165328202047372">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160630061730

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6164312189571364933">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6164312189571364933">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160728061610

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6166848903552036488">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6166848903552036488">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160804061611

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6174459048315007903">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6174459048315007903">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160825061612

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6176995762723512771">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6176995762723512771">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160901061617

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6179532486145950670">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6179532486145950670">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160908061619

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6184605910061227206">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6184605910061227206">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20160922061619

README.md
=> fixed typo insatall -> install

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6194752773297524640">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6194752773297524640">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20161020061634

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6197289485390270475">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6197289485390270475">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20161027061626

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6199826199610992327">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6199826199610992327">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20161103061631

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6207436345532206561">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6207436345532206561">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20161124061625

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6209973062803034741">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6209973062803034741">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20161201061637

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6215046496357501240">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6215046496357501240">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20161215061637

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6217583203979485022">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6217583203979485022">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20161222061655

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6225193352258276393">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6225193352258276393">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170112061606

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6240413648902388712">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6240413648902388712">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170223061606

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6248023790386377697">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6248023790386377697">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170316061606

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6250560498567473485">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6250560498567473485">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170323061603

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6255633928055483929">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6255633928055483929">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170406061603

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6258170647328507257">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6258170647328507257">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170413061603

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6260707360993560493">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6260707360993560493">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170420061602

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6263244084360450392">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6263244084360450392">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170427061604

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6265780790793769364">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6265780790793769364">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170504061602

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6278464365288221886">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6278464365288221886">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170608061602

Gemfile.lock
=> update mail gem

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6286074511037960201">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6286074511037960201">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170629061603

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6319547778798986987">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6319547778798986987">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20170929150651

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6324621209144694845">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6324621209144694845">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20171013150652

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6337304785174968688">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6337304785174968688">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20171117150651

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6339841503317400790">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6339841503317400790">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20171124150653

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6344914936280926563">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6344914936280926563">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20171208150653

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6347451643017851561">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6347451643017851561">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20171215150651

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6349988358034965962">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6349988358034965962">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20171222150659

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6357598501415812544">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6357598501415812544">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20180112150650

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6372818793011191225">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6372818793011191225">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20180223150652

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6380428937616534071">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6380428937616534071">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20180316150653

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6393112514405031542">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6393112514405031542">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20180420150652

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6400722657524872629">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6400722657524872629">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20180511150651

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6405796097917784079">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6405796097917784079">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20180525150654

Gemfile.lock
Powered by <a href="http://tachikoma.io/?utm_source=github&utm_medium=pull_request&utm_campaign=build6408332803943102621">Bundle Update as a Service - Tachikoma.io</a> <br />Announcement: <a href="http://tachikoma.io/2015-06-28-updated-permissions.html?utm_source=github&utm_medium=pull_request&utm_campaign=build6408332803943102621">2015-06-28 Updated permissions - Tachikoma.io</a>
=> Exec tachikoma update 20180601150651
